[package]
name = "bevy_editor_pls"
version = "0.1.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
edition = "2018"
exclude = ["docs/*"]

[features]

[dependencies]
bevy = { version = "0.5", default-features = false, features = ["render"] }
bevy-inspector-egui = "0.4"
bevy_mod_picking = { version = "0.4" }
bevy_fly_camera = "0.7"
bevy-orbit-controls = "2.0"
bevy_input_actionmap = { git = "https://github.com/lightsoutgames/bevy_input_actionmap" }

[dev-dependencies]
bevy = { version = "0.5", default-features = false, features = ["bevy_wgpu", "x11", "dynamic"] }
native-dialog = "0.5.5"
derive_more = "0.99.13"
ron = "0.6.2"

# [patch."https://github.com/bevyengine/bevy/"]
# bevy = { path = "/home/jakob/dev/rust/contrib/bevy/bevy" }

# [patch.crates-io]
# bevy = { path = '../bevy' }
# bevy-inspector-egui = { git = "https://github.com/jakobhellermann/bevy-inspector-egui", branch = "bevy-main" }